In [181]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten, BatchNormalization
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras import backend as K
from keras.utils import np_utils

In [182]:
display((df:=pd.read_csv('train.csv')).head())
display((dfT:=pd.read_csv('test.csv')).head())

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [183]:
display((X:=df.iloc[:,1:]).head())
display((Y:=df.iloc[:,0]).head())

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [184]:
X=X.values.tolist()
Y=Y.values.tolist()
X=np.asarray(X,dtype=np.float32)
Y=np.asarray(Y)

In [185]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [186]:
X_train=X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test=X_test.reshape(X_test.shape[0], 28, 28, 1)

In [187]:
X_train/=255
X_test/=255

In [188]:
model = Sequential()
model.add(Conv2D(28, kernel_size=(3,3), input_shape=(28, 28, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation=tf.nn.relu))
model.add(Dropout(0.2))
model.add(Dense(10,activation=tf.nn.softmax))

In [189]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x=X_train,y=Y_train, epochs=50)

Epoch 1/50
1050/1050 [==============================] - 8s 7ms/step - loss: 0.2713 - accuracy: 0.9182
Epoch 2/50
1050/1050 [==============================] - 7s 7ms/step - loss: 0.1068 - accuracy: 0.9663
Epoch 3/50
1050/1050 [==============================] - 8s 8ms/step - loss: 0.0762 - accuracy: 0.9758
Epoch 4/50
1050/1050 [==============================] - 8s 8ms/step - loss: 0.0561 - accuracy: 0.9816
Epoch 5/50
1050/1050 [==============================] - 8s 8ms/step - loss: 0.0409 - accuracy: 0.9867
Epoch 6/50
1050/1050 [==============================] - 9s 8ms/step - loss: 0.0336 - accuracy: 0.9891
Epoch 7/50
1050/1050 [==============================] - 8s 8ms/step - loss: 0.0263 - accuracy: 0.9913
Epoch 8/50
1050/1050 [==============================] - 9s 8ms/step - loss: 0.0261 - accuracy: 0.9910
Epoch 9/50
1050/1050 [==============================] - 9s 8ms/step - loss: 0.0210 - accuracy: 0.9932
Epoch 10/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0187 - accuracy: 0.9936
Epoch 11/50
1050/1050 [==============================] - 9s 9ms/step - loss: 0.0171 - accuracy: 0.9939
Epoch 12/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0195 - accuracy: 0.9933
Epoch 13/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0148 - accuracy: 0.9951
Epoch 14/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0148 - accuracy: 0.9948
Epoch 15/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0139 - accuracy: 0.9950
Epoch 16/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0121 - accuracy: 0.9960
Epoch 17/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0119 - accuracy: 0.9956
Epoch 18/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0117 - accuracy: 0.9959
Epoch 19/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0107 - accuracy: 0.9962
Epoch 20/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0083 - accuracy: 0.9971
Epoch 21/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0112 - accuracy: 0.9960
Epoch 22/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0113 - accuracy: 0.9965
Epoch 23/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0074 - accuracy: 0.9974
Epoch 24/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0092 - accuracy: 0.9968
Epoch 25/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0087 - accuracy: 0.9970
Epoch 26/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0071 - accuracy: 0.9973
Epoch 27/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0107 - accuracy: 0.9964
Epoch 28/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0098 - accuracy: 0.9970
Epoch 29/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0091 - accuracy: 0.9973
Epoch 30/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0067 - accuracy: 0.9975
Epoch 31/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0081 - accuracy: 0.9972
Epoch 32/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0061 - accuracy: 0.9981
Epoch 33/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0091 - accuracy: 0.9971
Epoch 34/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0069 - accuracy: 0.9976
Epoch 35/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0070 - accuracy: 0.9976
Epoch 36/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0086 - accuracy: 0.9974
Epoch 37/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0073 - accuracy: 0.9975
Epoch 38/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0056 - accuracy: 0.9982
Epoch 39/50
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0088 - accuracy: 0.9970
Epoch 40/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0065 - accuracy: 0.9982
Epoch 41/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0090 - accuracy: 0.9971
Epoch 42/50
1050/1050 [==============================] - 9s 9ms/step - loss: 0.0052 - accuracy: 0.9980
Epoch 43/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0075 - accuracy: 0.9976
Epoch 44/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0070 - accuracy: 0.9977
Epoch 45/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0071 - accuracy: 0.9979
Epoch 46/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0061 - accuracy: 0.9979
Epoch 47/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0085 - accuracy: 0.9974
Epoch 48/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0058 - accuracy: 0.9981
Epoch 49/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0072 - accuracy: 0.9977
Epoch 50/50
1050/1050 [==============================] - 10s 9ms/step - loss: 0.0069 - accuracy: 0.9979

In [190]:
model.evaluate(X_test, Y_test)

263/263 [==============================] - 1s 3ms/step - loss: 0.1179 - accuracy: 0.9837

[0.11788889765739441, 0.9836905002593994]

In [191]:
(dfS:=pd.read_csv('sub.csv')).head(5)

   ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [192]:
S=np.asarray(dfT.values.tolist(),dtype=np.float32)

In [193]:
S=S.reshape(dfT.shape[0], 28, 28, 1)

In [194]:
SS=model.predict(S)

In [195]:
SS.shape

(28000, 10)

In [196]:
q=[]
for i in SS:
    for j in range(10):
        if i[j]:
            q+=[j]
            break

In [197]:
dfS['Label']=q
dfS.head(10)

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3
5        6      7
6        7      0
7        8      3
8        9      0
9       10      3

In [198]:
dfS.to_csv('MINST_Submission.csv',index=False)